#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
# Class (1): Google Query Parameters
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
class Google_Parameters:

    #————————————————————————————————————————————————————————————————————————————————————————————————————
    # Function 1 : languages
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    def languages():
        langs_dict = {
                    'English': 'en',
                    'Arabic': 'ar',
                    'Armenian': 'hy',
                    'Belarusian': 'be',
                    'Bulgarian': 'bg',
                    'Catalan': 'ca',
                    'Croatian': 'hr',
                    'Czech': 'cs',
                    'Danish': 'da',
                    'Dutch': 'nl',
                    'Esperanto': 'eo',
                    'Estonian': 'et',
                    'Filipino': 'tl',
                    'Finnish': 'fi',
                    'French': 'fr',
                    'German': 'de',
                    'Greek': 'el',
                    'Hebrew': 'iw',
                    'Hungarian': 'hu',
                    'Icelandic': 'is',
                    'Indonesian': 'id',
                    'Italian': 'it',
                    'Japanese': 'ja',
                    'Korean': 'ko',
                    'Latvian': 'lv',
                    'Lithuanian': 'lt',
                    'Norwegian': 'no',
                    'Persian': 'fa',
                    'Polish': 'pl',
                    'Portuguese': 'pt',
                    'Romanian': 'ro',
                    'Russian': 'ru',
                    'Serbian': 'sr',
                    'Slovak': 'sk',
                    'Slovenian': 'sl',
                    'Spanish': 'es',
                    'Swedish': 'sv',
                    'Thai': 'th',
                    'Turkish': 'tr',
                    'Ukrainian': 'uk',
                    'Vietnamese': 'vi',
                    'Chinese Simplified': 'zh-CN',
                    'Chinese Traditional': 'zh-TW'}       
        
        return langs_dict
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    
    
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    # Function 2 : countries
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    def geolocation():
        geolocation = {
                    'Egypt': 'EG',
                    'Afghanistan': 'AF',
                    'Albania': 'AL',
                    'Algeria': 'DZ',
                    'American Samoa': 'AS',
                    'Andorra': 'AD',
                    'Angola': 'AO',
                    'Anguilla': 'AI',
                    'Antarctica': 'AQ',
                    'Antigua and Barbuda': 'AG',
                    'Argentina': 'AR',
                    'Armenia': 'AM',
                    'Aruba': 'AW',
                    'Australia': 'AU',
                    'Austria': 'AT',
                    'Azerbaijan': 'AZ',
                    'Bahamas': 'BS',
                    'Bahrain': 'BH',
                    'Bangladesh': 'BD',
                    'Barbados': 'BB',
                    'Belarus': 'BY',
                    'Belgium': 'BE',
                    'Belize': 'BZ',
                    'Benin': 'BJ',
                    'Bermuda': 'BM',
                    'Bhutan': 'BT',
                    'Bolivia': 'BO',
                    'Bosnia and Herzegovina': 'BA',
                    'Botswana': 'BW',
                    'Bouvet Island': 'BV',
                    'Brazil': 'BR',
                    'British Indian Ocean Territory': 'IO',
                    'Brunei Darussalam': 'BN',
                    'Bulgaria': 'BG',
                    'Burkina Faso': 'BF',
                    'Burundi': 'BI',
                    'Cambodia': 'KH',
                    'Cameroon': 'CM',
                    'Canada': 'CA',
                    'Cape Verde': 'CV',
                    'Cayman Islands': 'KY',
                    'Central African Republic': 'CF',
                    'Chad': 'TD',
                    'Chile': 'CL',
                    'China': 'CN',
                    'Christmas Island': 'CX',
                    'Cocos (Keeling) Islands': 'CC',
                    'Colombia': 'CO',
                    'Comoros': 'KM',
                    'Congo': 'CD',
                    'Cook Islands': 'CK',
                    'Costa Rica': 'CR',
                    "Cote d'Ivoire": 'CI',
                    'Croatia': 'HR',
                    'Cyprus': 'CY',
                    'Czech Republic': 'CZ',
                    'Denmark': 'DK',
                    'Djibouti': 'DJ',
                    'Dominica': 'DM',
                    'Dominican Republic': 'DO',
                    'East Timor': 'TL',
                    'Ecuador': 'EC',
                    'El Salvador': 'SV',
                    'Equatorial Guinea': 'GQ',
                    'Eritrea': 'ER',
                    'Estonia': 'EE',
                    'Ethiopia': 'ET',
                    'Falkland Islands (Malvinas)': 'FK',
                    'Faroe Islands': 'FO',
                    'Fiji': 'FJ',
                    'Finland': 'FI',
                    'France': 'FR',
                    'French Guiana': 'GF',
                    'French Polynesia': 'PF',
                    'French Southern Territories': 'TF',
                    'Gabon': 'GA',
                    'Gambia': 'GM',
                    'Georgia': 'GE',
                    'Germany': 'DE',
                    'Ghana': 'GH',
                    'Gibraltar': 'GI',
                    'Greece': 'GR',
                    'Greenland': 'GL',
                    'Grenada': 'GD',
                    'Guadeloupe': 'GP',
                    'Guam': 'GU',
                    'Guatemala': 'GT',
                    'Guinea': 'GN',
                    'Guinea-Bissau': 'GW',
                    'Guyana': 'GY',
                    'Haiti': 'HT',
                    'Heard and McDonald Islands': 'HM',
                    'Honduras': 'HN',
                    'Hong Kong': 'HK',
                    'Hungary': 'HU',
                    'Iceland': 'IS',
                    'India': 'IN',
                    'Indonesia': 'ID',
                    'Iraq': 'IQ',
                    'Ireland': 'IE',
                    'Israel': 'IL',
                    'Italy': 'IT',
                    'Jamaica': 'JM',
                    'Japan': 'JP',
                    'Jordan': 'JO',
                    'Kazakhstan': 'KZ',
                    'Kenya': 'KE',
                    'Kiribati': 'KI',
                    'Kuwait': 'KW',
                    'Kyrgyzstan': 'KG',
                    "Lao People's Democratic Republic": 'LA',
                    'Latvia': 'LV',
                    'Lebanon': 'LB',
                    'Lesotho': 'LS',
                    'Liberia': 'LR',
                    'Libya': 'LY',
                    'Liechtenstein': 'LI',
                    'Lithuania': 'LT',
                    'Luxembourg': 'LU',
                    'Macau': 'MO',
                    'Macedonia': 'MK',
                    'Madagascar': 'MG',
                    'Malawi': 'MW',
                    'Malaysia': 'MY',
                    'Maldives': 'MV',
                    'Mali': 'ML',
                    'Malta': 'MT',
                    'Marshall Islands': 'MH',
                    'Martinique': 'MQ',
                    'Mauritania': 'MR',
                    'Mauritius': 'MU',
                    'Mayotte': 'YT',
                    'Mexico': 'MX',
                    'Micronesia': 'FM',
                    'Moldova': 'MD',
                    'Monaco': 'MC',
                    'Mongolia': 'MN',
                    'Montserrat': 'MS',
                    'Morocco': 'MA',
                    'Mozambique': 'MZ',
                    'Namibia': 'NA',
                    'Nauru': 'NR',
                    'Nepal': 'NP',
                    'Netherlands': 'NL',
                    'Netherlands Antilles': 'AN',
                    'New Caledonia': 'NC',
                    'New Zealand': 'NZ',
                    'Nicaragua': 'NI',
                    'Niger': 'NE',
                    'Nigeria': 'NG',
                    'Niue': 'NU',
                    'Norfolk Island': 'NF',
                    'Northern Maria': 'MP',
                    'Norway': 'NO',
                    'Oman': 'OM',
                    'Pakistan': 'PK',
                    'Palau': 'PW',
                    'Palestinian Territory': 'PS',
                    'Panama': 'PA',
                    'Papua New Guinea': 'PG',
                    'Paraguay': 'PY',
                    'Peru': 'PE',
                    'Philippines': 'PH',
                    'Pitcairn': 'PN',
                    'Poland': 'PL',
                    'Portugal': 'PT',
                    'Puerto Rico': 'PR',
                    'Qatar': 'QA',
                    'Reunion': 'RE',
                    'Romania': 'RO',
                    'Russian Federation': 'RU',
                    'Rwanda': 'RW',
                    'Saint Kitts and Nevis': 'KN',
                    'Saint Lucia': 'LC',
                    'Saint Vincent and the Grenadines': 'VC',
                    'Samoa': 'WS',
                    'San Marino': 'SM',
                    'Sao Tome and Principe': 'ST',
                    'Saudi Arabia': 'SA',
                    'Senegal': 'SN',
                    'Serbia and Montenegro': 'CS',
                    'Seychelles': 'SC',
                    'Sierra Leone': 'SL',
                    'Singapore': 'SG',
                    'Slovakia': 'SK',
                    'Slovenia': 'SI',
                    'Solomon Islands': 'SB',
                    'Somalia': 'SO',
                    'South Africa': 'ZA',
                    'South Georgia and The South Sandwich Islands': 'GS',
                    'South Korea': 'KR',
                    'Spain': 'ES',
                    'Sri Lanka': 'LK',
                    'St. Helena': 'SH',
                    'St. Pierre and Miquelon': 'PM',
                    'Suriname': 'SR',
                    'Svalbard and Jan Mayen Islands': 'SJ',
                    'Swaziland': 'SZ',
                    'Sweden': 'SE',
                    'Switzerland': 'CH',
                    'Taiwan': 'TW',
                    'Tajikistan': 'TJ',
                    'Tanzania': 'TZ',
                    'Thailand': 'TH',
                    'Togo': 'TG',
                    'Tokelau': 'TK',
                    'Tonga': 'TO',
                    'Trinidad and Tobago': 'TT',
                    'Tunisia': 'TN',
                    'Turkey': 'TR',
                    'Turkmenistan': 'TM',
                    'Turks and Caicos Islands': 'TC',
                    'Tuvalu': 'TV',
                    'Uganda': 'UG',
                    'Ukraine': 'UA',
                    'United Arab Emirates': 'AE',
                    'United Kingdom': 'GB',
                    'United States': 'US',
                    'United States Minor Outlying Islands': 'UM',
                    'Uruguay': 'UY',
                    'Uzbekistan': 'UZ',
                    'Vanuatu': 'VU',
                    'Vatican': 'VA',
                    'Venezuela': 'VE',
                    'Viet Nam': 'VN',
                    'Virgin Islands (British)': 'VG',
                    'Virgin Islands (U.S.)': 'VI',
                    'Wallis and Futuna Islands': 'WF',
                    'Western Sahara': 'EH',
                    'Yemen': 'YE',
                    'Zambia': 'ZM',
                    'Zimbabwe': 'ZW'}
        
        return geolocation
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    # Function 3 : countries_acronyms
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    def countries_acronyms():
        countries = {
                    'Egypt': ['Egypt', 'Arab Republic of Egypt'],
                    'Aruba': ['Aruba', 'Aruba'],
                    'Afghanistan': ['Afghanistan', 'Islamic Republic of Afghanistan', 'IRA'],
                    'Angola': ['Angola', 'Republic of Angola'],
                    'Anguilla': ['Anguilla', 'Anguilla'],
                    'Åland Islands': ['Åland Islands', 'Åland Islands'],
                    'Albania': ['Albania', 'Republic of Albania'],
                    'Andorra': ['Andorra', 'Principality of Andorra'],
                    'United Arab Emirates': ['United Arab Emirates','United Arab Emirates','UAE'],
                    'Argentina': ['Argentina', 'Argentine Republic'],
                    'Armenia': ['Armenia', 'Republic of Armenia'],
                    'American Samoa': ['American Samoa', 'American Samoa'],
                    'Antarctica': ['Antarctica', 'Antarctica'],
                    'French Southern Territories': ['French Southern Territories','French Southern Territories','FST'],
                    'Antigua And Barbuda': ['Antigua and Barbuda', 'Antigua and Barbuda'],
                    'Australia': ['Australia', 'Australia'],
                    'Austria': ['Austria', 'Republic of Austria'],
                    'Azerbaijan': ['Azerbaijan', 'Republic of Azerbaijan'],
                    'Burundi': ['Burundi', 'Republic of Burundi'],
                    'Belgium': ['Belgium', 'Kingdom of Belgium'],
                    'Benin': ['Benin', 'Republic of Benin'],
                    'Bonaire, Sint Eustatius And Saba': ['Bonaire, Sint Eustatius and Saba','Bonaire, Sint Eustatius and Saba','BSEAS'],
                    'Burkina Faso': ['Burkina Faso', 'Burkina Faso'],
                    'Bangladesh': ['Bangladesh', "People's Republic of Bangladesh"],
                    'Bulgaria': ['Bulgaria', 'Republic of Bulgaria'],
                    'Bahrain': ['Bahrain', 'Kingdom of Bahrain'],
                    'Bahamas': ['Bahamas', 'Commonwealth of the Bahamas', 'CTB'],
                    'Bosnia And Herzegovina': ['Bosnia and Herzegovina','Republic of Bosnia and Herzegovina','RBAH'],
                    'Saint Barthélemy': ['Saint Barthélemy', 'Saint Barthélemy'],
                    'Belarus': ['Belarus', 'Republic of Belarus'],
                    'Belize': ['Belize', 'Belize'],
                    'Bermuda': ['Bermuda', 'Bermuda'],
                    'Bolivia, Plurinational State Of': ['Bolivia, Plurinational State of','Plurinational State of Bolivia','PSB'],
                    'Brazil': ['Brazil', 'Federative Republic of Brazil', 'FRB'],
                    'Barbados': ['Barbados', 'Barbados'],
                    'Brunei Darussalam': ['Brunei Darussalam', 'Brunei Darussalam'],
                    'Bhutan': ['Bhutan', 'Kingdom of Bhutan'],
                    'Bouvet Island': ['Bouvet Island', 'Bouvet Island'],
                    'Botswana': ['Botswana', 'Republic of Botswana'],
                    'Central African Republic': ['Central African Republic','Central African Republic','CAR'],
                    'Canada': ['Canada', 'Canada'],
                    'Cocos (Keeling) Islands': ['Cocos (Keeling) Islands','Cocos (Keeling) Islands'],
                    'Switzerland': ['Switzerland', 'Swiss Confederation'],
                    'Chile': ['Chile', 'Republic of Chile'],
                    'China': ['China', "People's Republic of China", 'PRC'],
                    "Côte D'Ivoire": ["Côte d'Ivoire", "Republic of Côte d'Ivoire", 'RCD'],
                    'Cameroon': ['Cameroon', 'Republic of Cameroon'],
                    'Congo, The Democratic Republic Of The': ['Congo, The Democratic Republic of thcfte','Congo, The Democratic Republic of the','CTDRT'],
                    'Congo': ['Congo', 'Republic of the Congo', 'RTC'],
                    'Cook Islands': ['Cook Islands', 'Cook Islands'],
                    'Colombia': ['Colombia', 'Republic of Colombia'],
                    'Comoros': ['Comoros', 'Union of the Comoros', 'UTC'],
                    'Cabo Verde': ['Cabo Verde', 'Republic of Cabo Verde', 'RCV'],
                    'Costa Rica': ['Costa Rica', 'Republic of Costa Rica', 'RCR'],
                    'Cuba': ['Cuba', 'Republic of Cuba'],
                    'Curaçao': ['Curaçao', 'Curaçao'],
                    'Christmas Island': ['Christmas Island', 'Christmas Island'],
                    'Cayman Islands': ['Cayman Islands', 'Cayman Islands'],
                    'Cyprus': ['Cyprus', 'Republic of Cyprus'],
                    'Czechia': ['Czechia', 'Czech Republic'],
                    'Germany': ['Germany', 'Federal Republic of Germany', 'FRG'],
                    'Djibouti': ['Djibouti', 'Republic of Djibouti'],
                    'Dominica': ['Dominica', 'Commonwealth of Dominica'],
                    'Denmark': ['Denmark', 'Kingdom of Denmark'],
                    'Dominican Republic': ['Dominican Republic', 'Dominican Republic'],
                    'Algeria': ['Algeria', "People's Democratic Republic of Algeria", 'PDRA'],
                    'Ecuador': ['Ecuador', 'Republic of Ecuador'],
                    'Eritrea': ['Eritrea', 'the State of Eritrea', 'TSE'],
                    'Western Sahara': ['Western Sahara', 'Western Sahara'],
                    'Spain': ['Spain', 'Kingdom of Spain'],
                    'Estonia': ['Estonia', 'Republic of Estonia'],
                    'Ethiopia': ['Ethiopia', 'Federal Democratic Republic of Ethiopia', 'FDRE'],
                    'Finland': ['Finland', 'Republic of Finland'],
                    'Fiji': ['Fiji', 'Republic of Fiji'],
                    'Falkland Islands (Malvinas)': ['Falkland Islands (Malvinas)',
                    'Falkland Islands (Malvinas)'],
                    'France': ['France', 'French Republic'],
                    'Faroe Islands': ['Faroe Islands', 'Faroe Islands'],
                    'Micronesia, Federated States Of': ['Micronesia, Federated States of','Federated States of Micronesia','FSM'],
                    'Gabon': ['Gabon', 'Gabonese Republic'],
                    'United Kingdom': ['United Kingdom','United Kingdom of Great Britain and Northern Ireland','UKGBANI'],
                    'Georgia': ['Georgia', 'Georgia'],
                    'Guernsey': ['Guernsey', 'Guernsey'],
                    'Ghana': ['Ghana', 'Republic of Ghana'],
                    'Gibraltar': ['Gibraltar', 'Gibraltar'],
                    'Guinea': ['Guinea', 'Republic of Guinea'],
                    'Guadeloupe': ['Guadeloupe', 'Guadeloupe'],
                    'Gambia': ['Gambia', 'Republic of the Gambia', 'RTG'],
                    'Guinea-Bissau': ['Guinea-Bissau', 'Republic of Guinea-Bissau'],
                    'Equatorial Guinea': ['Equatorial Guinea',
                    'Republic of Equatorial Guinea','REG'],
                    'Greece': ['Greece', 'Hellenic Republic'],
                    'Grenada': ['Grenada', 'Grenada'],
                    'Greenland': ['Greenland', 'Greenland'],
                    'Guatemala': ['Guatemala', 'Republic of Guatemala'],
                    'French Guiana': ['French Guiana', 'French Guiana'],
                    'Guam': ['Guam', 'Guam'],
                    'Guyana': ['Guyana', 'Republic of Guyana'],
                    'Hong Kong': ['Hong Kong','Hong Kong Special Administrative Region of China','HKSARC'],
                    'Heard Island And Mcdonald Islands': ['Heard Island and McDonald Islands','Heard Island and McDonald Islands','HIAMI'],
                    'Honduras': ['Honduras', 'Republic of Honduras'],
                    'Croatia': ['Croatia', 'Republic of Croatia'],
                    'Haiti': ['Haiti', 'Republic of Haiti'],
                    'Hungary': ['Hungary', 'Hungary'],
                    'Indonesia': ['Indonesia', 'Republic of Indonesia'],
                    'Isle Of Man': ['Isle of Man', 'Isle of Man'],
                    'India': ['India', 'Republic of India'],
                    'British Indian Ocean Territory': ['British Indian Ocean Territory','British Indian Ocean Territory','BIOT'],
                    'Ireland': ['Ireland', 'Ireland'],
                    'Iran, Islamic Republic Of': ['Iran, Islamic Republic of','Islamic Republic of Iran','IRI'],
                    'Iraq': ['Iraq', 'Republic of Iraq'],
                    'Iceland': ['Iceland', 'Republic of Iceland'],
                    'Israel': ['Israel', 'State of Israel'],
                    'Italy': ['Italy', 'Italian Republic'],
                    'Jamaica': ['Jamaica', 'Jamaica'],
                    'Jersey': ['Jersey', 'Jersey'],
                    'Jordan': ['Jordan', 'Hashemite Kingdom of Jordan'],
                    'Japan': ['Japan', 'Japan'],
                    'Kazakhstan': ['Kazakhstan', 'Republic of Kazakhstan'],
                    'Kenya': ['Kenya', 'Republic of Kenya'],
                    'Kyrgyzstan': ['Kyrgyzstan', 'Kyrgyz Republic'],
                    'Cambodia': ['Cambodia', 'Kingdom of Cambodia'],
                    'Kiribati': ['Kiribati', 'Republic of Kiribati'],
                    'Saint Kitts And Nevis': ['Saint Kitts and Nevis','Saint Kitts and Nevis','SKAN'],
                    'Korea, Republic Of': ['Korea, Republic of', 'Korea, Republic of'],
                    'Kuwait': ['Kuwait', 'State of Kuwait'],
                    "Lao People'S Democratic Republic": ["Lao People's Democratic Republic","Lao People's Democratic Republic",'LPDR'],
                    'Lebanon': ['Lebanon', 'Lebanese Republic'],
                    'Liberia': ['Liberia', 'Republic of Liberia'],
                    'Libya': ['Libya', 'Libya'],
                    'Saint Lucia': ['Saint Lucia', 'Saint Lucia'],
                    'Liechtenstein': ['Liechtenstein', 'Principality of Liechtenstein'],
                    'Sri Lanka': ['Sri Lanka','Democratic Socialist Republic of Sri Lanka','DSRSL'],
                    'Lesotho': ['Lesotho', 'Kingdom of Lesotho'],
                    'Lithuania': ['Lithuania', 'Republic of Lithuania'],
                    'Luxembourg': ['Luxembourg', 'Grand Duchy of Luxembourg', 'GDL'],
                    'Latvia': ['Latvia', 'Republic of Latvia'],
                    'Macao': ['Macao', 'Macao Special Administrative Region of China', 'MSARC'],
                    'Saint Martin (French Part)': ['Saint Martin (French part)','Saint Martin (French part)'],
                    'Morocco': ['Morocco', 'Kingdom of Morocco'],
                    'Monaco': ['Monaco', 'Principality of Monaco'],
                    'Moldova, Republic Of': ['Moldova, Republic of', 'Republic of Moldova'],
                    'Madagascar': ['Madagascar', 'Republic of Madagascar'],
                    'Maldives': ['Maldives', 'Republic of Maldives'],
                    'Mexico': ['Mexico', 'United Mexican States', 'UMS'],
                    'Marshall Islands': ['Marshall Islands','Republic of the Marshall Islands','RTMI'],
                    'North Macedonia': ['North Macedonia', 'Republic of North Macedonia', 'RNM'],
                    'Mali': ['Mali', 'Republic of Mali'],
                    'Malta': ['Malta', 'Republic of Malta'],
                    'Myanmar': ['Myanmar', 'Republic of Myanmar'],
                    'Montenegro': ['Montenegro', 'Montenegro'],
                    'Mongolia': ['Mongolia', 'Mongolia'],
                    'Northern Mariana Islands': ['Northern Mariana Islands','Commonwealth of the Northern Mariana Islands','CTNMI'],
                    'Mozambique': ['Mozambique', 'Republic of Mozambique'],
                    'Mauritania': ['Mauritania', 'Islamic Republic of Mauritania', 'IRM'],
                    'Montserrat': ['Montserrat', 'Montserrat'],
                    'Martinique': ['Martinique', 'Martinique'],
                    'Mauritius': ['Mauritius', 'Republic of Mauritius'],
                    'Malawi': ['Malawi', 'Republic of Malawi'],
                    'Malaysia': ['Malaysia', 'Malaysia'],
                    'Mayotte': ['Mayotte', 'Mayotte'],
                    'Namibia': ['Namibia', 'Republic of Namibia'],
                    'New Caledonia': ['New Caledonia', 'New Caledonia'],
                    'Niger': ['Niger', 'Republic of the Niger', 'RTN'],
                    'Norfolk Island': ['Norfolk Island', 'Norfolk Island'],
                    'Nigeria': ['Nigeria', 'Federal Republic of Nigeria', 'FRN'],
                    'Nicaragua': ['Nicaragua', 'Republic of Nicaragua'],
                    'Niue': ['Niue', 'Niue'],
                    'Netherlands': ['Netherlands', 'Kingdom of the Netherlands', 'KTN'],
                    'Norway': ['Norway', 'Kingdom of Norway'],
                    'Nepal': ['Nepal', 'Federal Democratic Republic of Nepal', 'FDRN'],
                    'Nauru': ['Nauru', 'Republic of Nauru'],
                    'New Zealand': ['New Zealand', 'New Zealand'],
                    'Oman': ['Oman', 'Sultanate of Oman'],
                    'Pakistan': ['Pakistan', 'Islamic Republic of Pakistan', 'IRP'],
                    'Panama': ['Panama', 'Republic of Panama'],
                    'Pitcairn': ['Pitcairn', 'Pitcairn'],
                    'Peru': ['Peru', 'Republic of Peru'],
                    'Philippines': ['Philippines', 'Republic of the Philippines', 'RTP'],
                    'Palau': ['Palau', 'Republic of Palau'],
                    'Papua New Guinea': ['Papua New Guinea','Independent State of Papua New Guinea','ISPNG'],
                    'Poland': ['Poland', 'Republic of Poland'],
                    'Puerto Rico': ['Puerto Rico', 'Puerto Rico'],
                    "Korea, Democratic People'S Republic Of": ["Korea, Democratic People's Republic of","Democratic People's Republic of Korea",'DPRK'],
                    'Portugal': ['Portugal', 'Portuguese Republic'],
                    'Paraguay': ['Paraguay', 'Republic of Paraguay'],
                    'Palestine, State Of': ['Palestine, State of','the State of Palestine','TSP'],
                    'French Polynesia': ['French Polynesia', 'French Polynesia'],
                    'Qatar': ['Qatar', 'State of Qatar'],
                    'Réunion': ['Réunion', 'Réunion'],
                    'Romania': ['Romania', 'Romania'],
                    'Russian Federation': ['Russian Federation', 'Russian Federation'],
                    'Rwanda': ['Rwanda', 'Rwandese Republic'],
                    'Saudi Arabia': ['Saudi Arabia', 'Kingdom of Saudi Arabia', 'KSA'],
                    'Sudan': ['Sudan', 'Republic of the Sudan', 'RTS'],
                    'Senegal': ['Senegal', 'Republic of Senegal'],
                    'Singapore': ['Singapore', 'Republic of Singapore'],
                    'South Georgia And The South Sandwich Islands': ['South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands','SGATSSI'],
                    'Saint Helena, Ascension And Tristan Da Cunha': ['Saint Helena, Ascension and Tristan da Cunha','Saint Helena, Ascension and Tristan da Cunha','SHAATDC'],
                    'Svalbard And Jan Mayen': ['Svalbard and Jan Mayen','Svalbard and Jan Mayen','SAJM'],
                    'Solomon Islands': ['Solomon Islands', 'Solomon Islands'],
                    'Sierra Leone': ['Sierra Leone', 'Republic of Sierra Leone', 'RSL'],
                    'El Salvador': ['El Salvador', 'Republic of El Salvador', 'RES'],
                    'San Marino': ['San Marino', 'Republic of San Marino', 'RSM'],
                    'Somalia': ['Somalia', 'Federal Republic of Somalia', 'FRS'],
                    'Saint Pierre And Miquelon': ['Saint Pierre and Miquelon','Saint Pierre and Miquelon'],
                    'Serbia': ['Serbia', 'Republic of Serbia'],
                    'South Sudan': ['South Sudan', 'Republic of South Sudan'],
                    'Sao Tome And Principe': ['Sao Tome and Principe','Democratic Republic of Sao Tome and Principe','DRSTAP'],
                    'Suriname': ['Suriname', 'Republic of Suriname'],
                    'Slovakia': ['Slovakia', 'Slovak Republic'],
                    'Slovenia': ['Slovenia', 'Republic of Slovenia'],
                    'Sweden': ['Sweden', 'Kingdom of Sweden'],
                    'Eswatini': ['Eswatini', 'Kingdom of Eswatini'],
                    'Sint Maarten (Dutch Part)': ['Sint Maarten (Dutch part)','Sint Maarten (Dutch part)'],
                    'Seychelles': ['Seychelles', 'Republic of Seychelles'],
                    'Syrian Arab Republic': ['Syrian Arab Republic','Syrian Arab Republic'],
                    'Turks And Caicos Islands': ['Turks and Caicos Islands','Turks and Caicos Islands','TACI'],
                    'Chad': ['Chad', 'Republic of Chad'],
                    'Togo': ['Togo', 'Togolese Republic'],
                    'Thailand': ['Thailand', 'Kingdom of Thailand'],
                    'Tajikistan': ['Tajikistan', 'Republic of Tajikistan'],
                    'Tokelau': ['Tokelau', 'Tokelau'],
                    'Turkmenistan': ['Turkmenistan', 'Turkmenistan'],
                    'Timor-Leste': ['Timor-Leste', 'Democratic Republic of Timor-Leste', 'DRT'],
                    'Tonga': ['Tonga', 'Kingdom of Tonga'],
                    'Trinidad And Tobago': ['Trinidad and Tobago',
                    'Republic of Trinidad and Tobago','RTAT'],
                    'Tunisia': ['Tunisia', 'Republic of Tunisia'],
                    'Türkiye': ['Türkiye', 'Republic of Türkiye'],
                    'Tuvalu': ['Tuvalu', 'Tuvalu'],
                    'Taiwan, Province Of China': ['Taiwan, Province of China','Taiwan, Province of China','TPC'],
                    'Tanzania, United Republic Of': ['Tanzania, United Republic of','United Republic of Tanzania','URT'],
                    'Uganda': ['Uganda', 'Republic of Uganda'],
                    'Ukraine': ['Ukraine', 'Ukraine'],
                    'United States Minor Outlying Islands': ['United States Minor Outlying Islands','United States Minor Outlying Islands','USMOI'],
                    'Uruguay': ['Uruguay', 'Eastern Republic of Uruguay', 'ERU'],
                    'United States': ['United States', 'United States of America', 'USA'],
                    'Uzbekistan': ['Uzbekistan', 'Republic of Uzbekistan'],
                    'Holy See (Vatican City State)': ['Holy See (Vatican City State)','Holy See (Vatican City State)'],
                    'Saint Vincent And The Grenadines': ['Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','SVATG'],
                    'Venezuela, Bolivarian Republic Of': ['Venezuela, Bolivarian Republic of','Bolivarian Republic of Venezuela','BRV'],
                    'Virgin Islands, British': ['Virgin Islands, British','British Virgin Islands','BVI'],
                    'Virgin Islands, U.S.': ['Virgin Islands, U.S.','Virgin Islands of the United States','VITUS'],
                    'Viet Nam': ['Viet Nam', 'Socialist Republic of Viet Nam', 'SRVN'],
                    'Vanuatu': ['Vanuatu', 'Republic of Vanuatu'],
                    'Wallis And Futuna': ['Wallis and Futuna', 'Wallis and Futuna', 'WAF'],
                    'Samoa': ['Samoa', 'Independent State of Samoa'],
                    'Yemen': ['Yemen', 'Republic of Yemen'],
                    'South Africa': ['South Africa', 'Republic of South Africa', 'RSA'],
                    'Zambia': ['Zambia', 'Republic of Zambia'],
                    'Zimbabwe': ['Zimbabwe', 'Republic of Zimbabwe']}
        return countries
    #————————————————————————————————————————————————————————————————————————————————————————————————————
 
    
    #————————————————————————————————————————————————————————————————————————————————————————————————————
    # Function 4 : term_apperaing_query
    #———————————————————————————————————————————————————————————————————————————————————————————————————— 
    def term_apperaing():
        term_dict = {
                'Anywhere': '',
                'In Title': 'allintitle: ',
                'In Text': 'allintext: ',
                'In URL': 'allinurl: ',
                'In Links': 'allinlinks: '}
        
        return term_dict
    #————————————————————————————————————————————————————————————————————————————————————————————————————
